/*
 * Copyright 2015 Shaheen Group.
 *
 * Contact by : s0552676097@gmail.com
 * All rights reserved !
 */
package az.shahin.swings;

import az.shahin.pojo.AccountPojo;
import az.shahin.pojo.LanguagePojo;
import az.shahin.pojo.TestsPojo;
import az.shahin.sql.AccountSQL;
import az.shahin.sql.TestsSQL;
import az.shahin.tests.AllLanguage;
import az.shahin.tests.Level;
import az.shahin.tests.Rate;
import az.shahin.tests.Rating;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Shahin Nazarov <s0552676097@gmail.com>
 */
public class SearchTests extends javax.swing.JDialog {

    private String username = "";
    java.awt.Frame Parent = null;

    public SearchTests(java.awt.Frame parent, boolean modal, String username) {
        super(parent, modal);
        Parent = parent;
        initComponents();
        this.username = username;
        start();
    }
    List<AccountPojo> acpojo = new ArrayList<>();

    private void start() {
        cmb_lang1.removeAllItems();
        cmb_Lang2.removeAllItems();
        cmb_level.removeAllItems();
        cmb_rate.removeAllItems();
        cmb_account.removeAllItems();
        cmb_lang1.addItem("Doesn't matter");
        cmb_account.addItem("Doesn't matter");
        cmb_account.addItem("Only Admin");
        cmb_account.addItem("Only User");
        cmb_Lang2.addItem("Doesn't matter");
        cmb_level.addItem("Doesn't matter");
        cmb_rate.addItem("Doesn't matter");
        for (LanguagePojo langpojo : AllLanguage.getAllLanguage()) {
            cmb_lang1.addItem(langpojo.getLanguage());
            cmb_Lang2.addItem(langpojo.getLanguage());
        }
        for (int i = 0; i <= 8; i++) {
            cmb_level.addItem(Level.getLevel(i));
        }
        for (String rating : Rate.getAllString()) {
            cmb_rate.addItem(rating);
        }
        acpojo = new AccountSQL().getAllData();
        for (AccountPojo pojo : acpojo) {
            cmb_account.addItem(pojo.getFirstname() + " " + pojo.getLastname());
        }

    }

    private static String query = null;

    public static String getQuery() {
        return query;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblWarning = new javax.swing.JLabel();
        btnPrev = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_score = new javax.swing.JTextField();
        cmb_Lang2 = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_desc = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        cmb_lang1 = new javax.swing.JComboBox();
        cmb_level = new javax.swing.JComboBox();
        cmb_rate = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnPrev1 = new javax.swing.JButton();
        cmb_pic = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        cmb_account = new javax.swing.JComboBox();
        cmb_date = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search Tests");
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(729, 380));

        lblWarning.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblWarning.setForeground(new java.awt.Color(102, 0, 153));
        lblWarning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWarning.setText("Searhing Tests");

        btnPrev.setBackground(new java.awt.Color(255, 255, 255));
        btnPrev.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnPrev.setForeground(new java.awt.Color(102, 0, 153));
        btnPrev.setText("Search");
        btnPrev.setOpaque(false);
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 51, 255));
        jLabel13.setText("Author of Test");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 51, 255));
        jLabel6.setText("Second Language");

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 51, 255));
        jLabel10.setText("Limit Score");

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 51, 255));
        jLabel14.setText("Sort Date");

        txt_score.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txt_score.setForeground(new java.awt.Color(153, 102, 255));
        txt_score.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_scoreKeyReleased(evt);
            }
        });

        cmb_Lang2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        cmb_Lang2.setForeground(new java.awt.Color(153, 102, 255));
        cmb_Lang2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txt_desc.setColumns(10);
        txt_desc.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txt_desc.setForeground(new java.awt.Color(153, 102, 255));
        txt_desc.setRows(5);
        txt_desc.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txt_desc);

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 51, 255));
        jLabel15.setText("Description");

        txt_id.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txt_id.setForeground(new java.awt.Color(153, 102, 255));
        txt_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_idKeyReleased(evt);
            }
        });

        cmb_lang1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        cmb_lang1.setForeground(new java.awt.Color(153, 102, 255));
        cmb_lang1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmb_level.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        cmb_level.setForeground(new java.awt.Color(153, 102, 255));
        cmb_level.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmb_rate.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        cmb_rate.setForeground(new java.awt.Color(153, 102, 255));
        cmb_rate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 51, 255));
        jLabel8.setText("Rating of Test");

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 51, 255));
        jLabel7.setText("Level of Test");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 51, 255));
        jLabel5.setText("First Language");

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 51, 255));
        jLabel9.setText("Only by Test Id");

        btnPrev1.setBackground(new java.awt.Color(255, 255, 255));
        btnPrev1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnPrev1.setForeground(new java.awt.Color(102, 0, 153));
        btnPrev1.setText("Close");
        btnPrev1.setOpaque(false);
        btnPrev1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrev1ActionPerformed(evt);
            }
        });

        cmb_pic.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        cmb_pic.setForeground(new java.awt.Color(153, 102, 255));
        cmb_pic.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Doesn't matter", "YES", "NO" }));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 51, 255));
        jLabel11.setText("Picture");

        cmb_account.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        cmb_account.setForeground(new java.awt.Color(153, 102, 255));
        cmb_account.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "RANDOM", "YES", "NO" }));

        cmb_date.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        cmb_date.setForeground(new java.awt.Color(153, 102, 255));
        cmb_date.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Doesn't matter", "New", "Old" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmb_lang1, 0, 169, Short.MAX_VALUE)
                                    .addComponent(txt_id, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)))
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel14))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmb_date, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_level, 0, 169, Short.MAX_VALUE)
                                    .addComponent(cmb_rate, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmb_account, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_score)
                                        .addComponent(cmb_Lang2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnPrev1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(123, 123, 123)
                                        .addComponent(jLabel15)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(55, 55, 55)
                                        .addComponent(cmb_pic, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmb_Lang2, cmb_account, cmb_date, cmb_lang1, cmb_level, cmb_rate, txt_id, txt_score});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_Lang2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_score, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_account, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_level, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_rate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_date, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmb_pic, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmb_lang1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPrev1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmb_Lang2, cmb_account, cmb_date, cmb_lang1, cmb_level, cmb_rate, txt_id, txt_score});

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        String sql = "Select * from tests where ";
        boolean or = false;
        if (txt_id.getText().length() > 0) {
            sql += " T_ID = " + txt_id.getText();
            or = true;
        } else {
            if (cmb_lang1.getSelectedIndex() > 0) {
                sql += (or ? " and " : " ") + " T_Lang1 = " + (cmb_lang1.getSelectedIndex() + 1);
                or = true;
            }

            if (cmb_Lang2.getSelectedIndex() > 0) {
                sql += (or ? " and " : " ") + " T_Lang2 = " + (cmb_Lang2.getSelectedIndex() + 1);
                or = true;
            }

            if (txt_score.getText().length() > 0) {
                sql += (or ? " and " : " ") + " T_Score >= " + txt_score.getText();
                or = true;
            }

            if (cmb_account.getSelectedIndex() != 0) {
                if (cmb_account.getSelectedIndex() == 1) {
                    sql += (or ? " and " : " ");
                    for (AccountPojo pojo : acpojo) {
                        if (pojo.getStatus() != 0) {
                            sql += " T_User = " + pojo.getId() + "  or";
                        }
                        or = true;

                    }
                    sql = sql.substring(0, sql.length() - 3);
                } else if (cmb_account.getSelectedIndex() == 2) {
                    sql += (or ? " and " : " ");
                    for (AccountPojo pojo : acpojo) {
                        if (pojo.getStatus() == 0) {
                            sql += " T_User = " + pojo.getId() + "  or";
                        }
                        or = true;

                    }
                    sql = sql.substring(0, sql.length() - 3);
                } else {
                    sql += (or ? " and " : " ") + " T_User = " + acpojo.get(cmb_account.getSelectedIndex() - 3).getId();
                    or = true;
                }
            }
            if (cmb_level.getSelectedIndex() > 0) {
                sql += (or ? " and " : " ") + " T_Lev = " + (cmb_level.getSelectedIndex() - 1);
                or = true;
            }
            if (cmb_rate.getSelectedIndex() > 0) {
                int rating = Rate.getRating(cmb_rate.getSelectedItem().toString());
                sql += (or ? " and " : " ") + " T_Rating <= " + rating;
                or = true;
            }

            if (cmb_pic.getSelectedIndex() == 0) {
                sql += (or ? " and " : " ") + " (T_Mode = 1 or T_Mode = 3) ";
                or = true;
            } else if (cmb_pic.getSelectedIndex() == 1) {
                sql += (or ? " and " : " ") + "  T_Mode = 3 ";
                or = true;
            } else {
                sql += (or ? " and " : " ") + " T_Mode = 1  ";
                or = true;
            }
            if (txt_desc.getText().length() > 0) {
                sql += (or ? " and " : " ") + " T_Description Like  '%" + txt_desc.getText() + "%' ";
                or = true;
            }
            if (cmb_date.getSelectedIndex() > 0) {
                sql += " Order By T_Date " + (cmb_date.getSelectedIndex() == 2 ? " DESC " : "");
            }
        }
        getList(sql);

    }//GEN-LAST:event_btnPrevActionPerformed
    private List<TestsPojo> tests = new ArrayList<>();

    private void getList(String query) {
       // System.out.println(query);
        List<TestsPojo> tests = new TestsSQL().getAllData(query);
        if (tests == null || tests.size() <= 0) {
            this.tests = null;
            int i =JOptionPane.showConfirmDialog(this, "no results matching your search filter", "Not Found", JOptionPane.WARNING_MESSAGE);
        } else {
            this.tests=tests;
            btnPrev1ActionPerformed(null);
        }
    }

    public List<TestsPojo> getTests() {
        return tests;
    }

    private void btnPrev1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrev1ActionPerformed
        this.dispose();
        this.setVisible(false);

// TODO add your handling code here:
    }//GEN-LAST:event_btnPrev1ActionPerformed

    private void txt_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idKeyReleased
        String intxt = txt_id.getText().trim();
        try {
            txt_id.setText(String.valueOf(Integer.parseInt(intxt)));
        } catch (Exception ex) {
            txt_id.setText("");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_txt_idKeyReleased

    private void txt_scoreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_scoreKeyReleased
        String intxt = txt_score.getText().trim();
        try {
            txt_score.setText(String.valueOf(Integer.parseInt(intxt)));
        } catch (Exception ex) {
            txt_score.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_scoreKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchTests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchTests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchTests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchTests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SearchTests dialog = new SearchTests(new javax.swing.JFrame(), true, "Admin");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnPrev;
    public javax.swing.JButton btnPrev1;
    public javax.swing.JComboBox cmb_Lang2;
    public javax.swing.JComboBox cmb_account;
    public javax.swing.JComboBox cmb_date;
    public javax.swing.JComboBox cmb_lang1;
    public javax.swing.JComboBox cmb_level;
    public javax.swing.JComboBox cmb_pic;
    public javax.swing.JComboBox cmb_rate;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel lblWarning;
    public javax.swing.JTextArea txt_desc;
    public javax.swing.JTextField txt_id;
    public javax.swing.JTextField txt_score;
    // End of variables declaration//GEN-END:variables
}
