/*
 * Copyright 2015 Shaheen Group.
 *
 * Contact by : s0552676097@gmail.com
 * All rights reserved !
 */
package az.shahin.swings;

import az.shahin.other.Admin;
import az.shahin.other.GenerateUUID;
import az.shahin.other.ImageOptions;
import az.shahin.other.OpenFile;
import az.shahin.other.TestModel;
import az.shahin.pojo.AccountPojo;
import az.shahin.pojo.LanguagePojo;
import az.shahin.pojo.TestsPojo;
import az.shahin.sql.AccountSQL;
import az.shahin.sql.TestsSQL;
import az.shahin.tests.AllLanguage;
import az.shahin.tests.Level;
import az.shahin.tests.Rate;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Shahin Nazarov <s0552676097@gmail.com>
 */
public class TestOperations extends javax.swing.JFrame {

    private AccountPojo pojo = null;
    private final int mode;

    private void start() {
        TestModel model = new TestModel(pojo.getId());
        if (searchresult != null) {
            model.start(searchresult);
        }
        lbl_mode.setVisible(false);
        cmb_mode.setVisible(false);
        if (Admin.isAdmin(pojo.getUsername())) {

            lbl_mode.setVisible(true);
            cmb_mode.setVisible(true);
        }
        tbl_test.removeAll();
        tbl_test.setModel(model);
        setTitle(pojo.getFirstname() + "'s Tests");
        lblUserDetails.setText("Welcome , " + pojo.getFirstname() + "  " + pojo.getLastname());
        group.add(btn_Show);
        group.add(btn_Update);
        group.add(btn_Delete);
        group.add(btn_Add);
        this.setSize(1010, 845);
        Thread thread = new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    Calendar calendar = new GregorianCalendar();
                    String date = null;
                    date = date.format("%02d/%02d/%04d   %02d : %02d : %02d", calendar.getTime().getDate(), calendar.getTime().getMonth() + 1, calendar.getTime().getYear() + 1900, calendar.getTime().getHours(), calendar.getTime().getMinutes(), calendar.getTime().getSeconds());
                    lblTime.setText(date);
                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException ex) {
                        //  Logger.getLogger(TestOperations.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
        thread.start();
        Training();
    }

    private void Training() {
        insertcmbBox();
        setPictureIcon("");
        setBtnEnble(false);
    }

    private void setBtnEnble(boolean set) {
        btnsave.setText("Save");
        txt_first.setEditable(set);
        txt_desc.setEditable(set);
        txt_second.setEditable(set);
        btnsave.setVisible(set);
        if (!set) {
            img_full.setEnabled(set);
            img_remove.setEnabled(set);
            img_up.setEnabled(set);
        } else {
            img_full.setEnabled(set);
            img_remove.setEnabled(set);
            img_up.setEnabled(set);
        }
        cmb_rate.setEnabled(true);
    }

    public TestOperations(String username, int mode) {
        if (username != null) {
            pojo = new AccountSQL().getAccountPojo(username);
        }
        this.mode = mode;
        initComponents();
        start();
        switch (mode) {
            case 1:
                btn_Show.setSelected(true);
                btn_ShowActionPerformed(null);
                break;
            case 2:
                btn_Add.setSelected(true);
                btn_AddActionPerformed(null);
                break;
            case 3:
                btn_Update.setSelected(true);
                btn_UpdateActionPerformed(null);
                break;
            case 4:
                btn_Delete.setSelected(true);
                btn_DeleteActionPerformed(null);
        }
    }

    /**
     * Creates new form EasyTestMaker
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_Delete = new javax.swing.JToggleButton();
        btn_Update = new javax.swing.JToggleButton();
        btn_Show = new javax.swing.JToggleButton();
        btn_Add = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblpic = new javax.swing.JLabel();
        img_full = new javax.swing.JButton();
        img_up = new javax.swing.JButton();
        img_remove = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmb_lang1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cmb_lang2 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cmb_level = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        cmb_rate = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_score = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_first = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_second = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_date = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_desc = new javax.swing.JTextArea();
        btnsave = new javax.swing.JButton();
        lbl_mode = new javax.swing.JLabel();
        cmb_mode = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();
        lblUserDetails = new javax.swing.JLabel();
        btn_Add1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_test = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setFocusTraversalPolicyProvider(true);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1005, 740));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setPreferredSize(new java.awt.Dimension(815, 100));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Test Box (Set Mode)");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(2, 0, 1000, 30);

        btn_Delete.setBackground(new java.awt.Color(255, 255, 255));
        btn_Delete.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btn_Delete.setForeground(new java.awt.Color(102, 0, 153));
        btn_Delete.setText("Delete Test");
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Delete);
        btn_Delete.setBounds(790, 40, 170, 50);

        btn_Update.setBackground(new java.awt.Color(255, 255, 255));
        btn_Update.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btn_Update.setForeground(new java.awt.Color(102, 0, 153));
        btn_Update.setText("Update Test");
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Update);
        btn_Update.setBounds(560, 40, 170, 50);

        btn_Show.setBackground(new java.awt.Color(255, 255, 255));
        btn_Show.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btn_Show.setForeground(new java.awt.Color(102, 0, 153));
        btn_Show.setText("Show Tests");
        btn_Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ShowActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Show);
        btn_Show.setBounds(40, 40, 170, 50);

        btn_Add.setBackground(new java.awt.Color(255, 255, 255));
        btn_Add.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btn_Add.setForeground(new java.awt.Color(102, 0, 153));
        btn_Add.setText("Add Test");
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Add);
        btn_Add.setBounds(290, 40, 170, 50);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(995, 320));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 330));

        lblpic.setPreferredSize(new java.awt.Dimension(41, 41));

        img_full.setBackground(new java.awt.Color(153, 51, 255));
        img_full.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        img_full.setForeground(new java.awt.Color(255, 255, 255));
        img_full.setText("Full Screen");
        img_full.setBorder(null);
        img_full.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                img_fullActionPerformed(evt);
            }
        });

        img_up.setBackground(new java.awt.Color(153, 51, 255));
        img_up.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        img_up.setForeground(new java.awt.Color(255, 255, 255));
        img_up.setText("Add or Update Picture");
        img_up.setBorder(null);
        img_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                img_upActionPerformed(evt);
            }
        });

        img_remove.setBackground(new java.awt.Color(153, 51, 255));
        img_remove.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        img_remove.setForeground(new java.awt.Color(255, 255, 255));
        img_remove.setText("Delete Picture");
        img_remove.setBorder(null);
        img_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                img_removeActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(51, 0, 51));
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Picture Options");
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 23));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(img_full, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(img_remove, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(lblpic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(img_up, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {img_full, img_remove, img_up});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblpic, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(img_full, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(img_up)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(img_remove)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {img_full, img_remove, img_up});

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(1000, 300));

        jLabel3.setBackground(new java.awt.Color(230, 228, 228));
        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 51, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Test Details");
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 23));

        cmb_lang1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        cmb_lang1.setForeground(new java.awt.Color(153, 102, 255));
        cmb_lang1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 51, 255));
        jLabel5.setText("First Language");

        cmb_lang2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        cmb_lang2.setForeground(new java.awt.Color(153, 102, 255));
        cmb_lang2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 51, 255));
        jLabel6.setText("Second Language");

        cmb_level.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        cmb_level.setForeground(new java.awt.Color(153, 102, 255));
        cmb_level.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 51, 255));
        jLabel7.setText("Level of Test");

        cmb_rate.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        cmb_rate.setForeground(new java.awt.Color(153, 102, 255));
        cmb_rate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 51, 255));
        jLabel8.setText("Rating of Test");

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 51, 255));
        jLabel9.setText("Number of Test");

        txt_id.setEditable(false);
        txt_id.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txt_id.setForeground(new java.awt.Color(153, 102, 255));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 51, 255));
        jLabel10.setText("Score Of Test");

        txt_score.setEditable(false);
        txt_score.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txt_score.setForeground(new java.awt.Color(153, 102, 255));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 51, 255));
        jLabel11.setText("First Word");

        txt_first.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txt_first.setForeground(new java.awt.Color(153, 102, 255));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 51, 255));
        jLabel12.setText("Second Word");

        txt_second.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txt_second.setForeground(new java.awt.Color(153, 102, 255));

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 51, 255));
        jLabel13.setText("Author of Test");

        txt_username.setEditable(false);
        txt_username.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txt_username.setForeground(new java.awt.Color(153, 102, 255));

        txt_date.setEditable(false);
        txt_date.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txt_date.setForeground(new java.awt.Color(153, 102, 255));

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 51, 255));
        jLabel14.setText("Last Updated date");

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 51, 255));
        jLabel15.setText("Describe");

        txt_desc.setColumns(10);
        txt_desc.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txt_desc.setForeground(new java.awt.Color(153, 102, 255));
        txt_desc.setRows(5);
        txt_desc.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txt_desc);

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        lbl_mode.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbl_mode.setForeground(new java.awt.Color(153, 51, 255));
        lbl_mode.setText("Mode *");

        cmb_mode.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        cmb_mode.setForeground(new java.awt.Color(153, 102, 255));
        cmb_mode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Active", "Deactive" }));
        cmb_mode.setSelectedIndex(1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb_level, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(cmb_lang2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb_rate, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel9))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmb_lang1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lbl_mode)
                        .addGap(109, 109, 109)
                        .addComponent(cmb_mode, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_second, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_first, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_score, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(65, 65, 65))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(txt_score, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_first, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_second, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_id)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_lang1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_lang2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_level, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_rate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_mode, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_mode, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txt_id, txt_score});

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setAlignmentY(0.0F);
        jPanel3.setPreferredSize(new java.awt.Dimension(815, 40));
        jPanel3.setLayout(null);

        lblTime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTime.setForeground(new java.awt.Color(102, 0, 153));
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime.setText("Easy Test Maker");
        lblTime.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.lightGray));
        lblTime.setPreferredSize(new java.awt.Dimension(300, 30));
        jPanel3.add(lblTime);
        lblTime.setBounds(670, 10, 300, 30);

        lblUserDetails.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblUserDetails.setForeground(new java.awt.Color(102, 0, 153));
        lblUserDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserDetails.setText("Easy Test Maker");
        lblUserDetails.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.lightGray));
        lblUserDetails.setPreferredSize(new java.awt.Dimension(500, 30));
        jPanel3.add(lblUserDetails);
        lblUserDetails.setBounds(0, 10, 417, 30);

        btn_Add1.setBackground(new java.awt.Color(255, 255, 255));
        btn_Add1.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        btn_Add1.setForeground(new java.awt.Color(102, 0, 153));
        btn_Add1.setText("<< Return to Main Page");
        btn_Add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Add1ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Add1);
        btn_Add1.setBounds(420, 10, 250, 30);

        tbl_test.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_test.setRowHeight(25);
        tbl_test.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_testMouseClicked(evt);
            }
        });
        tbl_test.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_testKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_test);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ShowActionPerformed

        setBtnEnble(false);
        searchresult = null;
        if (tbl_test.getSelectedRow() == -1) {
            img_full.setEnabled(false);
            img_remove.setEnabled(false);
            img_up.setEnabled(false);
            btnsave.setVisible(true);
        } else {
            tbl_testMouseClicked(null);
        }
        btnsave.setVisible(false);
        if (Admin.isAdmin(pojo.getUsername())) {
            btnsave.setVisible(true);
        }
        btnsave.setText("Search");
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ShowActionPerformed

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        // TODO add your handling code here:
        setBtnEnble(true);

        if (tbl_test.getSelectedRow() == -1) {
            img_full.setEnabled(false);
            img_remove.setEnabled(false);
            img_up.setEnabled(false);
            btnsave.setVisible(false);
        } else {
            tbl_testMouseClicked(null);
        }
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed

        setBtnEnble(false);

        if (tbl_test.getSelectedRow() == -1) {
            img_full.setEnabled(false);
            img_remove.setEnabled(false);
            img_up.setEnabled(false);
            btnsave.setVisible(false);
        } else {
            tbl_testMouseClicked(null);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void img_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_img_removeActionPerformed
        img_remove.setEnabled(false);
        setPictureIcon("");
        path = "";
        // TODO add your handling code here:
    }//GEN-LAST:event_img_removeActionPerformed

    private void img_fullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_img_fullActionPerformed
        OpenFile.openFile(new File("img/" + (path.endsWith(".jpg") ? path : path + ".jpg")));

    }//GEN-LAST:event_img_fullActionPerformed

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
        setBtnEnble(true);
        setPictureIcon("");
        txt_id.setText("Auto Generated");
        txt_score.setText("Auto Generated");
        txt_date.setText("Auto Generated");
        txt_username.setText(pojo.getFirstname() + " " + pojo.getLastname());
        txt_first.setText("");
        txt_second.setText("");
        txt_desc.setText("");
        cmb_rate.setSelectedIndex(0);
        cmb_rate.setEnabled(false);
    }//GEN-LAST:event_btn_AddActionPerformed


    private void img_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_img_upActionPerformed
        String text = "";
        if (cmb_lang1.getSelectedIndex() == 14) {
            text = txt_first.getText();
        } else if (cmb_lang2.getSelectedIndex() == 14) {
            text = txt_second.getText();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Please type search text in international format !");
        }
        new ImageUpdate(this, true, path, text).setVisible(true);
        //System.out.println(ImageUpdate.getFileLocation());
        if (ImageUpdate.getFileLocation() != null) {
            path = ImageUpdate.getFileLocation();
            setPictureIcon(ImageUpdate.getFileLocation());
        }
    }//GEN-LAST:event_img_upActionPerformed
    private void deleteTest() {
        if (tbl_test.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Select one item !", "ERROR", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String password = JOptionPane.showInputDialog(null, "Please type old password , and confirm operation", "Confirm Operation", JOptionPane.QUESTION_MESSAGE);
        if (password != null && password.equals(pojo.getPassword())) {
            new TestsSQL().DeleteData(Integer.parseInt(tbl_test.getModel().getValueAt(tbl_test.getSelectedRow(), 0).toString()));
            JOptionPane.showMessageDialog(this, "Sucessfully deleted", "OK", JOptionPane.PLAIN_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Password incorrect", "Wrong Password", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void updateTest() {
        if (txt_first.getText().trim().length() < 2) {
            JOptionPane.showMessageDialog(this, "First word's length is small", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (txt_second.getText().trim().length() < 2) {
            JOptionPane.showMessageDialog(this, "Second word's length is small", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (txt_desc.getText().trim().length() < 2) {
            JOptionPane.showMessageDialog(this, "Description's length is small", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            TestsPojo pojo = new TestsPojo();
            pojo.setLang1(cmb_lang1.getSelectedIndex());
            pojo.setLang2(cmb_lang2.getSelectedIndex());
            pojo.setLevel(cmb_level.getSelectedIndex());
            pojo.setDescription(txt_desc.getText());
            pojo.setQuestion(txt_first.getText());
            pojo.setAnswer(txt_second.getText());
            pojo.setAccount(this.pojo.getId());
            pojo.setId(Integer.parseInt(tbl_test.getModel().getValueAt(tbl_test.getSelectedRow(), 0).toString()));
            pojo.setPicture("");
            pojo.setMode(0);
            int modeprosda = 0;
            if (cmb_mode.getSelectedIndex() == 0) {
                modeprosda = 1;
            }
            if (path.length() > 4) {
                if (path.length() < 30) {
                    try {
                        String path2 = path;
                        path = GenerateUUID.getGeneratedUUID();
                        ImageOptions.copyFile(new File("img/" + (path2.endsWith(".jpg") ? (path2) : (path2 + ".jpg"))), path + ".jpg");
                    } catch (IOException ex) {
                        Logger.getLogger(ImageUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    }
                }
                pojo.setPicture(path);
                if (cmb_mode.getSelectedIndex() == 0) {
                    modeprosda = 3;
                } else {
                    modeprosda = 2;
                }

            }
            pojo.setMode(modeprosda);
            Integer score = (txt_first.getText().length() + (cmb_level.getSelectedIndex() + 1)) * txt_second.getText().length();
            pojo.setScore(score);
            new TestsSQL().UpdateData(pojo);
            JOptionPane.showMessageDialog(this, "Sucessfully Updated", "OK", JOptionPane.PLAIN_MESSAGE);
        }
    }

    private void addTest() {
        if (txt_first.getText().trim().length() < 2) {
            JOptionPane.showMessageDialog(this, "First word's length is small", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (txt_second.getText().trim().length() < 2) {
            JOptionPane.showMessageDialog(this, "Second word's length is small", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (txt_desc.getText().trim().length() < 2) {
            JOptionPane.showMessageDialog(this, "Description's length is small", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            TestsPojo pojo = new TestsPojo();
            pojo.setLang1(cmb_lang1.getSelectedIndex());
            pojo.setLang2(cmb_lang2.getSelectedIndex());
            pojo.setLevel(cmb_level.getSelectedIndex());
            pojo.setDescription(txt_desc.getText());
            pojo.setQuestion(txt_first.getText());
            pojo.setAnswer(txt_second.getText());
            pojo.setAccount(this.pojo.getId());
            pojo.setPicture("");
            int modeprosda = 0;
            if (cmb_mode.getSelectedIndex() == 0) {
                modeprosda = 1;
            }
            if (path.length() > 4) {
                if (path.length() < 30) {
                    try {
                        String path2 = path;
                        path = GenerateUUID.getGeneratedUUID();
                        ImageOptions.copyFile(new File("img/" + (path2.endsWith(".jpg") ? (path2) : (path2 + ".jpg"))), path + ".jpg");
                    } catch (IOException ex) {
                        Logger.getLogger(ImageUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    }
                }
                if (cmb_mode.getSelectedIndex() == 0) {
                    modeprosda = 3;
                } else {
                    modeprosda = 2;
                }
                pojo.setPicture(path);

            }
            pojo.setMode(modeprosda);
            Integer score = (txt_first.getText().length() + (cmb_level.getSelectedIndex() + 1)) * txt_second.getText().length();
            pojo.setScore(score);
            new TestsSQL().InserData(pojo);
            JOptionPane.showMessageDialog(this, "Sucessfully inserted", "OK", JOptionPane.PLAIN_MESSAGE);
        }
    }
    List<TestsPojo> searchresult = null;
    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        int mode = 0;
        if (btn_Show.isSelected()) {
            SearchTests search = new SearchTests(this, true, pojo.getUsername());
            search.show();
            btn_Show.setSelected(true);
            if (search.getTests() != null || search.getTests().size() > 0) {
                searchresult = search.getTests();
            } else {
                searchresult = null;
            }
        } else if (tbl_test.getSelectedRow() != -1 && btn_Delete.isSelected()) {
            deleteTest();
            mode = 1;
        } else if (tbl_test.getSelectedRow() != -1 && btn_Update.isSelected()) {
            updateTest();
            mode = 2;
        } else if (btn_Add.isSelected()) {
            addTest();
            mode = 3;
        }
        start();
        btnsave.setVisible(true);
        if (mode == 0) {
            btn_ShowActionPerformed(evt);
        } else if (mode == 1) {
            btn_DeleteActionPerformed(evt);
        } else if (mode == 2) {
            btn_UpdateActionPerformed(evt);
        } else if (mode == 3) {
            btn_AddActionPerformed(evt);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btn_Add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Add1ActionPerformed
        EasyTestMaker maker = new EasyTestMaker(pojo.getUsername());
        this.dispose();
        this.setVisible(false);
        maker.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Add1ActionPerformed

    private void tbl_testMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_testMouseClicked
        btnsave.setText("Search");
        if (btn_Add.isSelected()) {
            btnsave.setText("Save");
            img_full.setEnabled(false);
            img_up.setEnabled(true);
            img_remove.setEnabled(false);
            btnsave.setVisible(true);
            return;
        } else if (btn_Show.isSelected()) {
            btnsave.setText("Search");
            btnsave.setVisible(true);
        }
        if (tbl_test.getSelectedRow() >= -1) {
            if (btn_Update.isSelected()) {
                img_full.setEnabled(true);
                img_up.setEnabled(true);
                img_remove.setEnabled(true);
                btnsave.setVisible(true);
            } else if (btn_Show.isSelected() || btn_Delete.isSelected()) {
                img_full.setEnabled(true);
                img_up.setEnabled(false);
                img_remove.setEnabled(false);
                if (btn_Delete.isSelected()) {
                    btnsave.setVisible(true);
                    btnsave.setText("Delete");
                }
            }

            InsertPanels(Integer.parseInt(tbl_test.getModel().getValueAt(tbl_test.getSelectedRow(), 0).toString()));
        }// TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_testMouseClicked

    private void tbl_testKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_testKeyReleased
        // TODO add your handling code here:
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP) {
            tbl_testMouseClicked(null);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_testKeyReleased

    private void setPictureIcon(String picture) {
        if (picture.length() > 2) {
            picture = picture.endsWith(".jpg") ? picture : (picture + ".jpg");
            img_full.setEnabled(true);
            img_remove.setEnabled(false);
            if (btn_Update.isSelected()) {
                img_remove.setEnabled(true);
            }
            BufferedImage img = ImageOptions.setResalution(176, 176, picture);
            // System.out.println("Set Picture" + picture);
            lblpic.setIcon(new ImageIcon(img));
            path = picture;
        } else {
            img_full.setEnabled(false);
            img_remove.setEnabled(false);
            BufferedImage img = ImageOptions.setResalution(176, 176, "07046d2f-bc6e-4291-b60f-a18e652f16f7.jpg");
            lblpic.setIcon(new ImageIcon(img));
            path = "";
        }
    }

    private void InsertPanels(int id) {
        insertcmbBox();
        TestsPojo model = new TestsSQL().getTestoPjo(id);
        setPictureIcon(model.getPicture());
        txt_id.setEnabled(false);
        txt_id.setText(String.valueOf(id));
        if (btn_Update.isSelected()) {
            img_up.setEnabled(true);
        }
        cmb_lang1.setSelectedItem(AllLanguage.getLanguage(model.getLang1()));
        cmb_lang2.setSelectedItem(AllLanguage.getLanguage(model.getLang2()));
        cmb_level.setSelectedItem(Level.getLevel(model.getLevel()));
        cmb_rate.setSelectedItem(Rate.getRating(model.getRating()));
        txt_score.setText(String.valueOf(model.getScore()));
        txt_username.setText(tbl_test.getModel().getValueAt(tbl_test.getSelectedRow(), 5).toString());
        txt_date.setText(tbl_test.getModel().getValueAt(tbl_test.getSelectedRow(), 8).toString());
        txt_desc.setText(model.getDescription());
        txt_first.setText(model.getQuestion());
        txt_second.setText(model.getAnswer());
        cmb_mode.setSelectedIndex(1);
        if (model.getMode() == 1 || model.getMode() == 3) {
            cmb_mode.setSelectedIndex(0);
        }
    }
    private String path = "";

    private void insertcmbBox() {
        cmb_lang1.removeAllItems();
        cmb_lang2.removeAllItems();
        cmb_level.removeAllItems();
        cmb_rate.removeAllItems();
        for (LanguagePojo langpojo : AllLanguage.getAllLanguage()) {
            cmb_lang1.addItem(langpojo.getLanguage());
            cmb_lang2.addItem(langpojo.getLanguage());
        }
        for (int i = 0; i <= 8; i++) {
            cmb_level.addItem(Level.getLevel(i));
        }
        for (String rating : Rate.getAllString()) {
            cmb_rate.addItem(rating);
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JToggleButton btn_Add;
    public javax.swing.JToggleButton btn_Add1;
    public javax.swing.JToggleButton btn_Delete;
    public javax.swing.JToggleButton btn_Show;
    public javax.swing.JToggleButton btn_Update;
    public javax.swing.JButton btnsave;
    public javax.swing.JComboBox cmb_lang1;
    public javax.swing.JComboBox cmb_lang2;
    public javax.swing.JComboBox cmb_level;
    public javax.swing.JComboBox cmb_mode;
    public javax.swing.JComboBox cmb_rate;
    public javax.swing.ButtonGroup group;
    public javax.swing.JButton img_full;
    public javax.swing.JButton img_remove;
    public javax.swing.JButton img_up;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JPanel jPanel6;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel lblTime;
    public javax.swing.JLabel lblUserDetails;
    public javax.swing.JLabel lbl_mode;
    public javax.swing.JLabel lblpic;
    public javax.swing.JTable tbl_test;
    public javax.swing.JTextField txt_date;
    public javax.swing.JTextArea txt_desc;
    public javax.swing.JTextField txt_first;
    public javax.swing.JTextField txt_id;
    public javax.swing.JTextField txt_score;
    public javax.swing.JTextField txt_second;
    public javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
