/*
 * Copyright 2015 Shaheen Group.
 *
 * Contact by : s0552676097@gmail.com
 * All rights reserved !
 */
package az.shahin.swings;

import az.shahin.other.Admin;
import az.shahin.other.UserModel;
import az.shahin.other.Validator;
import az.shahin.pojo.AccountPojo;
import az.shahin.sql.AccountSQL;
import az.shahin.sql.HighScoreSQL;
import az.shahin.sql.TestsSQL;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Shahin Nazarov <s0552676097@gmail.com>
 */
public class UserTools extends javax.swing.JFrame {

    private final int mode;
    private AccountPojo pojo = null;

    private void start() {
        UserModel model = new UserModel(Admin.isAdmin(pojo.getUsername()));
        tbl_test.setModel(model);
        setTitle(pojo.getFirstname() + "'s Tests");
        lblUserDetails.setText("Welcome , " + pojo.getFirstname() + "  " + pojo.getLastname());
        this.setSize(783, 832);
        Thread thread = new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    Calendar calendar = new GregorianCalendar();
                    String date = null;
                    date = date.format("%02d/%02d/%04d   %02d : %02d : %02d", calendar.getTime().getDate(), calendar.getTime().getMonth() + 1, calendar.getTime().getYear() + 1900, calendar.getTime().getHours(), calendar.getTime().getMinutes(), calendar.getTime().getSeconds());
                    lblTime.setText(date);
                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException ex) {
                        //  Logger.getLogger(TestOperations.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
        thread.start();
        Training();
        group.add(btn_filter);
        group.add(btn_delete);
        group.add(btn_update);
        group.add(btn_enter);
        switch (mode) {
            case 0:
                btn_filter.setSelected(true);
                btn_filterActionPerformed(null);
                break;
            case 1:
                btn_update.setSelected(true);
                btn_updateActionPerformed(null);
                break;
            case 2:
                btn_delete.setSelected(true);
                btn_deleteActionPerformed(null);
                break;
            case 3:
                btn_enter.setSelected(true);
                btn_enterActionPerformed(null);
                break;
        }

    }

    private void setAdmin(boolean a) {
        lbl_mode.setVisible(a);
        btn_delete.setVisible(a);
        // btn_filter.setVisible(a);
        btn_update.setVisible(a);
        btn_enter.setVisible(a);
        jLabel16.setVisible(a);
        jLabel17.setVisible(a);
        jLabel18.setVisible(a);
        jLabel19.setVisible(a);
        txt_mail.setVisible(a);
        txt_password.setVisible(a);
        txt_username.setVisible(a);
        cmb_status.setVisible(a);
        btnsave.setVisible(a);
    }

    private void txtEditables(boolean cmd) {
        txt_mail.setEditable(cmd);
        txt_password.setEditable(cmd);
        txt_username.setEditable(cmd);
        txt_first.setEditable(cmd);
        txt_score.setEditable(cmd);
        txt_second.setEditable(cmd);
        txt_tel.setEditable(cmd);
    }

    private void Training() {
        if (!Admin.isAdmin(pojo.getUsername())) {
            setAdmin(false);
        } else {
            setAdmin(true);
        }
    }

    public UserTools(String username, int mode) {
        if (username != null) {
            pojo = new AccountSQL().getAccountPojo(username);
        }
        this.mode = mode;
        initComponents();
        start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();
        lblUserDetails = new javax.swing.JLabel();
        btn_Add1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblWarning = new javax.swing.JLabel();
        cmb_gender = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_score = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_first = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_second = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_tel = new javax.swing.JTextField();
        txt_mail = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        cmb_status = new javax.swing.JComboBox();
        txt_password = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        lbl_mode = new javax.swing.JLabel();
        btn_enter = new javax.swing.JToggleButton();
        btn_filter = new javax.swing.JToggleButton();
        btn_update = new javax.swing.JToggleButton();
        btn_delete = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_test = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setFocusTraversalPolicyProvider(true);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(790, 850));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setPreferredSize(new java.awt.Dimension(815, 30));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("User Search");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(2, 0, 780, 30);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setAlignmentY(0.0F);
        jPanel3.setPreferredSize(new java.awt.Dimension(815, 40));
        jPanel3.setLayout(null);

        lblTime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTime.setForeground(new java.awt.Color(102, 0, 153));
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime.setText("Easy Test Maker");
        lblTime.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.lightGray));
        lblTime.setPreferredSize(new java.awt.Dimension(300, 30));
        jPanel3.add(lblTime);
        lblTime.setBounds(470, 10, 300, 30);

        lblUserDetails.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUserDetails.setForeground(new java.awt.Color(102, 0, 153));
        lblUserDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserDetails.setText("Easy Test Maker");
        lblUserDetails.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.lightGray));
        lblUserDetails.setPreferredSize(new java.awt.Dimension(500, 30));
        jPanel3.add(lblUserDetails);
        lblUserDetails.setBounds(10, 10, 290, 30);

        btn_Add1.setBackground(new java.awt.Color(255, 255, 255));
        btn_Add1.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        btn_Add1.setForeground(new java.awt.Color(102, 0, 153));
        btn_Add1.setText("<<Main Page");
        btn_Add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Add1ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Add1);
        btn_Add1.setBounds(300, 10, 170, 31);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(995, 320));
        jPanel1.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(1000, 300));

        lblWarning.setBackground(new java.awt.Color(230, 228, 228));
        lblWarning.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblWarning.setForeground(new java.awt.Color(153, 51, 255));
        lblWarning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWarning.setText("User Details");
        lblWarning.setPreferredSize(new java.awt.Dimension(200, 23));

        cmb_gender.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        cmb_gender.setForeground(new java.awt.Color(153, 102, 255));
        cmb_gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 51, 255));
        jLabel7.setText("Gender");

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 51, 255));
        jLabel9.setText("User's ID");

        txt_id.setEditable(false);
        txt_id.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txt_id.setForeground(new java.awt.Color(153, 102, 255));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 51, 255));
        jLabel10.setText("Score Of User");

        txt_score.setEditable(false);
        txt_score.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txt_score.setForeground(new java.awt.Color(153, 102, 255));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 51, 255));
        jLabel11.setText("First Name");

        txt_first.setEditable(false);
        txt_first.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txt_first.setForeground(new java.awt.Color(153, 102, 255));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 51, 255));
        jLabel12.setText("Last Name");

        txt_second.setEditable(false);
        txt_second.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txt_second.setForeground(new java.awt.Color(153, 102, 255));

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 51, 255));
        jLabel13.setText("Telephone");

        txt_tel.setEditable(false);
        txt_tel.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txt_tel.setForeground(new java.awt.Color(153, 102, 255));

        txt_mail.setEditable(false);
        txt_mail.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txt_mail.setForeground(new java.awt.Color(153, 102, 255));

        btnsave.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnsave.setForeground(new java.awt.Color(153, 102, 255));
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 51, 255));
        jLabel16.setText("Status*");

        cmb_status.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        cmb_status.setForeground(new java.awt.Color(153, 102, 255));
        cmb_status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "User" }));

        txt_password.setEditable(false);
        txt_password.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txt_password.setForeground(new java.awt.Color(153, 102, 255));

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 51, 255));
        jLabel17.setText("Password*");

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 51, 255));
        jLabel18.setText("Username*");

        txt_username.setEditable(false);
        txt_username.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        txt_username.setForeground(new java.awt.Color(153, 102, 255));

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 51, 255));
        jLabel19.setText("E-Mail*");

        lbl_date.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbl_date.setForeground(new java.awt.Color(153, 51, 255));
        lbl_date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_date.setText("Date");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmb_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(86, 93, Short.MAX_VALUE)
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_second, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_first, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_score, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(93, 93, 93)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmb_status, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(btnsave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lbl_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(397, 397, 397))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(lblWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txt_id, txt_second});

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmb_gender, cmb_status, txt_tel});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_id)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txt_first, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_second, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_date, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_score, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsave)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_status, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txt_id, txt_score});

        jPanel1.add(jPanel5);
        jPanel5.setBounds(10, 460, 780, 290);

        lbl_mode.setBackground(new java.awt.Color(230, 228, 228));
        lbl_mode.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbl_mode.setForeground(new java.awt.Color(153, 51, 255));
        lbl_mode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_mode.setText("Select Mode");
        lbl_mode.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel1.add(lbl_mode);
        lbl_mode.setBounds(0, 343, 777, 40);

        btn_enter.setBackground(new java.awt.Color(255, 255, 255));
        btn_enter.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btn_enter.setForeground(new java.awt.Color(102, 0, 153));
        btn_enter.setText("Enter As User*");
        btn_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enterActionPerformed(evt);
            }
        });
        jPanel1.add(btn_enter);
        btn_enter.setBounds(590, 400, 180, 50);

        btn_filter.setBackground(new java.awt.Color(255, 255, 255));
        btn_filter.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btn_filter.setForeground(new java.awt.Color(102, 0, 153));
        btn_filter.setText("Filter");
        btn_filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_filterActionPerformed(evt);
            }
        });
        jPanel1.add(btn_filter);
        btn_filter.setBounds(20, 400, 150, 50);

        btn_update.setBackground(new java.awt.Color(255, 255, 255));
        btn_update.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btn_update.setForeground(new java.awt.Color(102, 0, 153));
        btn_update.setText("Update*");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_update);
        btn_update.setBounds(210, 400, 150, 50);

        btn_delete.setBackground(new java.awt.Color(255, 255, 255));
        btn_delete.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(102, 0, 153));
        btn_delete.setText("Delete*");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete);
        btn_delete.setBounds(400, 400, 150, 50);

        tbl_test.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_test.setRowHeight(25);
        tbl_test.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_testMouseClicked(evt);
            }
        });
        tbl_test.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_testKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_test);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(12, 10, 750, 340);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private boolean isSelected() {
        boolean isselected = true;
        if (tbl_test.getSelectedRow() == -1) {
            isselected = false;
        }
        return isselected;
    }

    private void deleteTest() {
        if (tbl_test.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Select one item !", "ERROR", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String password = JOptionPane.showInputDialog(null, "Please type old password , and confirm operation(You delete this user's account, this user's all tests,score)", "Confirm Operation", JOptionPane.QUESTION_MESSAGE);
        if (password != null && password.equals(pojo.getPassword())) {
            if (Admin.isAdmin(txt_username.getText())) {
                int i = JOptionPane.showConfirmDialog(this, "This user is Admin!Do you want continue this process ?", "Confirmation", JOptionPane.WARNING_MESSAGE);
                if (i != 0) {
                    return;
                }
            }
            new AccountSQL().DeleteData(Integer.parseInt(tbl_test.getModel().getValueAt(tbl_test.getSelectedRow(), 0).toString()));
            UserModel model = new UserModel(Admin.isAdmin(pojo.getUsername()));
            if (SearchResult != null && SearchResult.size() > 0) {
                model.setData(SearchResult);
            }
            tbl_test.setModel(model);
            JOptionPane.showMessageDialog(this, "Sucessfully deleted", "OK", JOptionPane.PLAIN_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Password incorrect", "Wrong Password", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void updateTest() {

        lblWarning.setText("");
        lblWarning.setForeground(Color.red);
        if (txt_first.getText().length() < 3 || txt_first.getText().length() > 19) {
            lblWarning.setText("FirstName is too small (or large) ");
        } else if (txt_second.getText().length() < 3 || txt_second.getText().length() > 19) {
            lblWarning.setText("LastName is too small (or large) ");
        } else if (txt_password.getText().length() < 5 || txt_password.getText().length() > 19) {
            lblWarning.setText("Password is too small (or large) ");
        } else if (!txt_password.getText().equals(txt_password.getText())) {
            lblWarning.setText("Again type password error");
        } else if (txt_mail.getText().length() > 34 || !Validator.isValidEmailAddress(txt_mail.getText())) {
            lblWarning.setText("Invalid Email adress  (or large) ");
        } else if (!String.valueOf(tbl_test.getModel().getValueAt(tbl_test.getSelectedRow(), 8)).equals(txt_mail.getText()) && new AccountSQL().RegistrationCheck(txt_mail.getText(), false) == 1) {
            lblWarning.setText("This Email already exist");
        } else if (!Validator.isValidNumber(txt_tel.getText()) || txt_tel.getText().length() > 13) {
            lblWarning.setText("Invalid Telephone number (or large) ");
        } else {
            String password = JOptionPane.showInputDialog(null, "Please type old password", "Confirm Password", JOptionPane.QUESTION_MESSAGE);
            if (password != null && password.equals(pojo.getPassword())) {
                AccountPojo pojoec = new AccountPojo(Integer.parseInt(txt_id.getText()), txt_username.getText(), txt_first.getText(), txt_second.getText(), txt_tel.getText(), txt_mail.getText(), txt_password.getText(), cmb_gender.getSelectedIndex() == 0 ? 'M' : 'F', cmb_status.getSelectedIndex() == 0 ? 8456565 : 0, null);
                new AccountSQL().UpdateData(pojoec);
                if (!String.valueOf(tbl_test.getModel().getValueAt(tbl_test.getSelectedRow(), 0)).equals(txt_score.getText())) {
                    int number = 0;
                    try {
                        number = Integer.parseInt(txt_score.getText());
                    } catch (Exception ex) {

                    }
                    new HighScoreSQL().Update(txt_username.getText(), number);
                }
                UserModel model = new UserModel(Admin.isAdmin(pojo.getUsername()));
                if (SearchResult != null && SearchResult.size() > 0) {
                    model.setData(SearchResult);
                }
                tbl_test.setModel(model);
                JOptionPane.showMessageDialog(this, "Sucessfully Updated", "OK", JOptionPane.PLAIN_MESSAGE);
            }
            lblWarning.setText("Invalid password !");
        }

    }

    private void btn_Add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Add1ActionPerformed
        EasyTestMaker maker = new EasyTestMaker(pojo.getUsername());
        this.dispose();
        this.setVisible(false);
        maker.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Add1ActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        if (tbl_test.getSelectedRow() >= 0) {
            if (btn_update.isSelected()) {
                updateTest();
            } else if (btn_delete.isSelected()) {
                deleteTest();
            } else if (btn_enter.isSelected()) {
                this.dispose();
                this.setVisible(false);
                new EasyTestMaker(txt_username.getText()).show();
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btn_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enterActionPerformed
        txtEditables(false);
        btnsave.setVisible(true);
        btnsave.setText("Go");
    }//GEN-LAST:event_btn_enterActionPerformed
    List<AccountPojo> SearchResult = new ArrayList<>();
    private void btn_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_filterActionPerformed
        txtEditables(false);
        btnsave.setVisible(false);
        SearchUser usersearc = new SearchUser(this, true);
        usersearc.setVisible(true);
        SearchResult = usersearc.getTests();
        UserModel model = new UserModel(Admin.isAdmin(pojo.getUsername()));
        if (SearchResult != null && SearchResult.size() > 0) {
            model.setData(SearchResult);
        }
        tbl_test.setModel(model);

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_filterActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed

        txtEditables(true);
        btnsave.setVisible(true);
        btnsave.setText("Update");
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        txtEditables(false);
        btnsave.setVisible(true);
        btnsave.setText("Delete");
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void tbl_testMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_testMouseClicked

        if (tbl_test.getSelectedRow() >= 0) {
            InsertPanels(tbl_test.getSelectedRow());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_testMouseClicked

    private void tbl_testKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_testKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP) {
            tbl_testMouseClicked(null);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_testKeyReleased

    private void InsertPanels(int row) {
        txt_id.setText(String.valueOf(tbl_test.getModel().getValueAt(row, 0)));
        txt_first.setText(String.valueOf(tbl_test.getModel().getValueAt(row, 1)));
        txt_second.setText(String.valueOf(tbl_test.getModel().getValueAt(row, 2)));
        if (tbl_test.getModel().getValueAt(row, 3).equals("Male")) {
            cmb_gender.setSelectedIndex(0);
        } else {
            cmb_gender.setSelectedIndex(1);
        }
        txt_tel.setText(String.valueOf(tbl_test.getModel().getValueAt(row, 4)));
        txt_score.setText(String.valueOf(tbl_test.getModel().getValueAt(row, 5)));
        if (Admin.isAdmin(pojo.getUsername())) {
            txt_username.setText(String.valueOf(tbl_test.getModel().getValueAt(row, 6)));
            txt_password.setText(String.valueOf(tbl_test.getModel().getValueAt(row, 7)));
            txt_mail.setText(String.valueOf(tbl_test.getModel().getValueAt(row, 8)));
            if (tbl_test.getModel().getValueAt(row, 9).equals("Admin")) {
                cmb_status.setSelectedIndex(0);
            } else {
                cmb_status.setSelectedIndex(1);
            }
            lbl_date.setText("Date : " + String.valueOf(tbl_test.getModel().getValueAt(row, 10)));
        } else {
            lbl_date.setText("Date : " + String.valueOf(tbl_test.getModel().getValueAt(row, 6)));
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserTools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserTools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserTools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserTools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JToggleButton btn_Add1;
    public javax.swing.JToggleButton btn_delete;
    public javax.swing.JToggleButton btn_enter;
    public javax.swing.JToggleButton btn_filter;
    public javax.swing.JToggleButton btn_update;
    public javax.swing.JButton btnsave;
    public javax.swing.JComboBox cmb_gender;
    public javax.swing.JComboBox cmb_status;
    public javax.swing.ButtonGroup group;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel lblTime;
    public javax.swing.JLabel lblUserDetails;
    public javax.swing.JLabel lblWarning;
    public javax.swing.JLabel lbl_date;
    public javax.swing.JLabel lbl_mode;
    public javax.swing.JTable tbl_test;
    public javax.swing.JTextField txt_first;
    public javax.swing.JTextField txt_id;
    public javax.swing.JTextField txt_mail;
    public javax.swing.JTextField txt_password;
    public javax.swing.JTextField txt_score;
    public javax.swing.JTextField txt_second;
    public javax.swing.JTextField txt_tel;
    public javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
